// flow-typed signature: be401c31c75dfa64d9a6607bfa1e27d9
// flow-typed version: <<STUB>>/eslint-config-starnavi-react_v^1.0.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-starnavi-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-starnavi-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-starnavi-react/rules/best-practices' {
  declare module.exports: any;
}

declare module 'eslint-config-starnavi-react/rules/errors' {
  declare module.exports: any;
}

declare module 'eslint-config-starnavi-react/rules/es6' {
  declare module.exports: any;
}

declare module 'eslint-config-starnavi-react/rules/imports' {
  declare module.exports: any;
}

declare module 'eslint-config-starnavi-react/rules/node' {
  declare module.exports: any;
}

declare module 'eslint-config-starnavi-react/rules/react-a11y' {
  declare module.exports: any;
}

declare module 'eslint-config-starnavi-react/rules/react' {
  declare module.exports: any;
}

declare module 'eslint-config-starnavi-react/rules/strict' {
  declare module.exports: any;
}

declare module 'eslint-config-starnavi-react/rules/style' {
  declare module.exports: any;
}

declare module 'eslint-config-starnavi-react/rules/variables' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-starnavi-react/index' {
  declare module.exports: $Exports<'eslint-config-starnavi-react'>;
}
declare module 'eslint-config-starnavi-react/index.js' {
  declare module.exports: $Exports<'eslint-config-starnavi-react'>;
}
declare module 'eslint-config-starnavi-react/rules/best-practices.js' {
  declare module.exports: $Exports<'eslint-config-starnavi-react/rules/best-practices'>;
}
declare module 'eslint-config-starnavi-react/rules/errors.js' {
  declare module.exports: $Exports<'eslint-config-starnavi-react/rules/errors'>;
}
declare module 'eslint-config-starnavi-react/rules/es6.js' {
  declare module.exports: $Exports<'eslint-config-starnavi-react/rules/es6'>;
}
declare module 'eslint-config-starnavi-react/rules/imports.js' {
  declare module.exports: $Exports<'eslint-config-starnavi-react/rules/imports'>;
}
declare module 'eslint-config-starnavi-react/rules/node.js' {
  declare module.exports: $Exports<'eslint-config-starnavi-react/rules/node'>;
}
declare module 'eslint-config-starnavi-react/rules/react-a11y.js' {
  declare module.exports: $Exports<'eslint-config-starnavi-react/rules/react-a11y'>;
}
declare module 'eslint-config-starnavi-react/rules/react.js' {
  declare module.exports: $Exports<'eslint-config-starnavi-react/rules/react'>;
}
declare module 'eslint-config-starnavi-react/rules/strict.js' {
  declare module.exports: $Exports<'eslint-config-starnavi-react/rules/strict'>;
}
declare module 'eslint-config-starnavi-react/rules/style.js' {
  declare module.exports: $Exports<'eslint-config-starnavi-react/rules/style'>;
}
declare module 'eslint-config-starnavi-react/rules/variables.js' {
  declare module.exports: $Exports<'eslint-config-starnavi-react/rules/variables'>;
}
